% GW_550_PSA1__LKA_main_switch
% GW_550_PSA1__LC_Mode
% EPS_495_PSA1__State_of_EPS_for_LKA_function
% EPS_495_PSA1__Steering_wheel_torque
% ESC_3CD_PSA1__Lateral_acceleration
% ESC_3CD_PSA1__Yaw_speed
% ESC_38D_PSA1__Vehicle_speed_of_wheelsensor
% GW_32D_PSA1__ACCEL_LONGI_CALIB
% ESC_3CD_PSA1__TMC_pressure
% EPS_305_PSA1__Steering_wheel_angle
% EPS_305_PSA1__Steering_wheel_rotation_speed
% GW_452_PSA1__BCM_Status_Indicator
% GW_349_PSA1__TCU_Gear_lever_position
% Video_Lane_Left_A__C3_5FA
% Video_Lane_Left_A__C2_5FA
% Video_Lane_Left_A__C1_5FA
% Video_Lane_Left_A__C0_5FA
% Video_Lane_Left_A__Quality_5FA
% Video_Lane_Left_A__Line_Type_5FA
% Video_Lane_Left_B__View_Range_5FC
% Video_Lane_Left_B__TLC_5FC
% Video_Lane_Right_A__C3_5FD
% Video_Lane_Right_A__C2_5FD
% Video_Lane_Right_A__C1_5FD
% Video_Lane_Right_A__C0_5FD
% Video_Lane_Right_A__Quality_5FD
% Video_Lane_Right_A__Line_Type_5FD
% Video_Lane_Right_B__View_Range_5FF
% Video_Lane_Right_B__TLC_5FF
% Video_Lane_Left_A__C0_5FA
% Video_Lane_Left_A__C1_5FA
% Video_Lane_Left_A__C2_5FA
% Video_Lane_Left_A__C3_5FA
% Video_Lane_Left_B__View_Range_5FC
% Video_Lane_Left_A__Quality_5FA
% Video_Lane_Left_A__Line_Type_5FA
% Video_Lane_Left_B__TLC_5FC
% Video_Lane_Right_A__C0_5FD
% Video_Lane_Right_A__C1_5FD
% Video_Lane_Right_A__C2_5FD
% Video_Lane_Right_A__C3_5FD
% Video_Lane_Right_B__View_Range_5FF
% Video_Lane_Right_A__Quality_5FD
% Video_Lane_Right_A__Line_Type_5FD
% Video_Lane_Right_B__TLC_5FF
% ADAS_541_PSA1__LDW_Flag
% ADAS_541_PSA1__Vehicle_Lane_Display
% ADAS_3F2_PSA1__Column_angle_setpoint3F2
% ADAS_3F2_PSA1__Permit_to_know_if_LKA_or_LPA3F2