% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Oct-2021 17:19:59
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
                            

ob_LKA_Disable_Reason = Simulink.Signal;
ob_LKA_Disable_Reason.CoderInfo.StorageClass = 'Custom';
ob_LKA_Disable_Reason.CoderInfo.Alias = '';
ob_LKA_Disable_Reason.CoderInfo.Alignment = -1;
ob_LKA_Disable_Reason.CoderInfo.CustomStorageClass = 'Default';
ob_LKA_Disable_Reason.Description = '';
ob_LKA_Disable_Reason.DataType = 'single';
ob_LKA_Disable_Reason.Min = 0;
ob_LKA_Disable_Reason.Max = 1;
ob_LKA_Disable_Reason.DocUnits = '';
ob_LKA_Disable_Reason.Dimensions = -1;
ob_LKA_Disable_Reason.DimensionsMode = 'auto';
ob_LKA_Disable_Reason.Complexity = 'auto';
ob_LKA_Disable_Reason.SampleTime = -1;
ob_LKA_Disable_Reason.InitialValue = '';

ob_LKA_LKADeactvCSyn = Simulink.Signal;
ob_LKA_LKADeactvCSyn.CoderInfo.StorageClass = 'Custom';
ob_LKA_LKADeactvCSyn.CoderInfo.Alias = '';
ob_LKA_LKADeactvCSyn.CoderInfo.Alignment = -1;
ob_LKA_LKADeactvCSyn.CoderInfo.CustomStorageClass = 'Default';
ob_LKA_LKADeactvCSyn.Description = '';
ob_LKA_LKADeactvCSyn.DataType = 'single';
ob_LKA_LKADeactvCSyn.Min = 0;
ob_LKA_LKADeactvCSyn.Max = 2;
ob_LKA_LKADeactvCSyn.DocUnits = '';
ob_LKA_LKADeactvCSyn.Dimensions = -1;
ob_LKA_LKADeactvCSyn.DimensionsMode = 'auto';
ob_LKA_LKADeactvCSyn.Complexity = 'auto';
ob_LKA_LKADeactvCSyn.SampleTime = -1;
ob_LKA_LKADeactvCSyn.InitialValue = '';

ob_LKA_Version = Simulink.Signal;
ob_LKA_Version.CoderInfo.StorageClass = 'Custom';
ob_LKA_Version.CoderInfo.Alias = '';
ob_LKA_Version.CoderInfo.Alignment = -1;
ob_LKA_Version.CoderInfo.CustomStorageClass = 'Default';
ob_LKA_Version.Description = '';
ob_LKA_Version.DataType = 'single';
ob_LKA_Version.Min = [];
ob_LKA_Version.Max = [];
ob_LKA_Version.DocUnits = '';
ob_LKA_Version.Dimensions = -1;
ob_LKA_Version.DimensionsMode = 'auto';
ob_LKA_Version.Complexity = 'auto';
ob_LKA_Version.SampleTime = -1;
ob_LKA_Version.InitialValue = '';

